name: Build Android APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
      
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 17
      
      - uses: gradle/gradle-build-action@v2.4.2
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ReadYou-WeChat-Style
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30